// @ts-check

/** @typedef {import('../contract/content.js').Product} Product */

/** @param {string} name @param {string} alt */
const img = (name, alt) => ({ src: `/images/placeholder/${name}.jpg`, alt });

/**
 * Prices are per piece, from the live site (owner's screenshot, 3 Oct 2026).
 * Minimum 10 pieces (owner, 8 Oct 2026); staff can set a product's own minimum in the back office
 * (Products), which the order form follows once orders run on the API. Descriptions and options are
 * a first draft.
 */
const MIN = 10;

/** @type {Product[]} */
export const products = [
  {
    slug: 'business-cards',
    name: 'Business cards',
    category: 'stationery',
    service: 'stationery',
    pricePerPiece: 18,
    minQuantity: MIN,
    summary: 'Full colour, both sides, on heavy card.',
    description:
      'Printed in full colour on 400 gsm card that feels solid in the hand. Send your design or let our studio set it up from your logo.',
    options: [
      { name: 'Finish', values: ['Matte laminate', 'Gloss laminate', 'Soft-touch'] },
      { name: 'Sides', values: ['Both sides', 'One side'] },
    ],
    image: img('business-cards-stack', 'Stacks of blank business cards'),
    featured: true,
  },
  {
    slug: 'a5-posters',
    name: 'A5 posters',
    category: 'print',
    service: 'stationery',
    pricePerPiece: 28,
    minQuantity: MIN,
    summary: 'Bright, full-colour flyers and posters.',
    description: 'A5 flyers and posters for menus, offers and events, printed in bright full colour.',
    options: [{ name: 'Paper', values: ['Gloss 150 gsm', 'Matte 170 gsm'] }],
    image: img('print-samples', 'Printed brochures and design books on a white table'),
    featured: false,
  },
  {
    slug: 'brochures',
    name: 'Brochures',
    category: 'print',
    service: 'stationery',
    pricePerPiece: 50,
    minQuantity: MIN,
    summary: 'Folded brochures for menus, price lists and company profiles.',
    description: 'A4 brochures folded to fit a pocket or a counter stand, on silk paper that takes colour well.',
    options: [{ name: 'Fold', values: ['Tri-fold', 'Bi-fold', 'Z-fold'] }],
    image: img('brochure', 'A folded brochure standing on a beige surface'),
    featured: false,
  },
  {
    slug: 'booklet-printing',
    name: 'Booklet printing',
    category: 'print',
    service: 'stationery',
    pricePerPiece: 700,
    minQuantity: MIN,
    summary: 'Stapled or perfect-bound booklets and company profiles.',
    description: 'Company profiles, catalogues and reports, stapled or with a glued spine, with a heavy laminated cover.',
    options: [{ name: 'Binding', values: ['Saddle-stitched', 'Perfect bound'] }],
    image: img('booklet', 'A plain hardcover book standing on a grey background'),
    featured: false,
  },
  {
    slug: 'a4-notebooks',
    name: 'A4 notebooks',
    category: 'stationery',
    service: 'corporate-gifts',
    pricePerPiece: 1200,
    minQuantity: MIN,
    summary: 'Branded covers, your choice of ruled or plain pages.',
    description: 'Spiral-bound A4 notebooks with your design on a laminated cover. Good for staff, events and gift sets.',
    options: [{ name: 'Pages', values: ['Ruled', 'Plain', 'Dotted'] }],
    image: img('notebook', 'A spiral notebook on a grey background'),
    featured: true,
  },
  {
    slug: 'water-bottle-branding',
    name: 'Water bottle branding',
    category: 'gifts',
    service: 'corporate-gifts',
    pricePerPiece: 800,
    minQuantity: MIN,
    summary: 'Metal bottles printed or engraved with your logo.',
    description: 'Insulated steel bottles that keep drinks cold all day, with your logo printed in colour or laser engraved.',
    options: [
      { name: 'Branding', values: ['Printed', 'Laser engraved'] },
      { name: 'Colour', values: ['White', 'Black', 'Silver', 'Blue'] },
    ],
    image: img('water-bottles', 'Three pastel metal water bottles'),
    featured: true,
  },
  {
    slug: 'mug-branding',
    name: 'Mug branding',
    category: 'gifts',
    service: 'corporate-gifts',
    pricePerPiece: 450,
    minQuantity: MIN,
    summary: 'Ceramic mugs printed to survive the dishwasher.',
    description: 'Classic 11 oz mugs printed all the way round. The print is baked in, so it lasts through daily washing.',
    options: [{ name: 'Mug', values: ['White ceramic', 'Colour-change', 'Enamel'] }],
    image: img('mug', 'A white mug of coffee with a printed logo'),
    featured: true,
  },
  {
    slug: 'umbrella-branding',
    name: 'Umbrella branding',
    category: 'gifts',
    service: 'corporate-gifts',
    pricePerPiece: 1500,
    minQuantity: MIN,
    summary: 'Large umbrellas with your logo on every panel.',
    description: 'Strong, wind-resistant umbrellas with your logo printed on the panels you choose. Seen all through the rainy season.',
    options: [{ name: 'Size', values: ['Golf (30 inch)', 'Standard (23 inch)'] }],
    image: img('umbrellas', 'Colourful open umbrellas against the sky'),
    featured: false,
  },
  {
    slug: 'hoodie-branding',
    name: 'Hoodie branding',
    category: 'apparel',
    service: 'apparel',
    pricePerPiece: 2500,
    minQuantity: MIN,
    summary: 'Heavy hoodies, printed or embroidered.',
    description: 'Warm, heavy hoodies in all sizes, with your design printed or embroidered on the chest, back or sleeve.',
    options: [
      { name: 'Branding', values: ['Print', 'Embroidery'] },
      { name: 'Colour', values: ['Black', 'Navy', 'Grey', 'White'] },
    ],
    image: img('hoodie', 'A plain white hoodie hanging on a rope'),
    featured: false,
  },
  {
    slug: 't-shirt-printing',
    name: 'T-shirt printing',
    category: 'apparel',
    service: 'apparel',
    pricePerPiece: 650,
    minQuantity: MIN,
    summary: 'Screen or heat-transfer printing for teams and events.',
    description: 'Cotton t-shirts in every size, printed for staff, teams and events. Tell us the sizes when we send the proof.',
    options: [
      { name: 'Print', values: ['Screen print', 'Heat transfer'] },
      { name: 'Colour', values: ['White', 'Black', 'Navy', 'Red'] },
    ],
    image: img('tshirts-folded', 'Three folded t-shirts in blue, sand and pale blue'),
    featured: true,
  },
  {
    slug: 'branded-gift-bags',
    name: 'Branded gift bags',
    category: 'gifts',
    service: 'corporate-gifts',
    pricePerPiece: 430,
    minQuantity: MIN,
    summary: 'Paper gift bags with rope handles and your logo.',
    description: 'Paper bags with rope handles, printed with your logo. For shops, events and gift sets.',
    options: [{ name: 'Size', values: ['Medium', 'Small', 'Large'] }],
    image: img('kraft-bag', 'A brown paper gift bag on a marble counter'),
    featured: false,
  },
  {
    slug: 'banner-stands',
    name: 'Banner stands',
    category: 'display',
    service: 'large-format',
    pricePerPiece: 3500,
    minQuantity: MIN,
    summary: 'Roll-up banners with stand and carry bag.',
    description: 'An 85 × 200 cm roll-up banner with its stand and carry bag. Up in a minute at any event.',
    options: [{ name: 'Stand', values: ['Economy roll-up', 'Premium roll-up', 'X-banner'] }],
    image: img('banner-outdoor', 'A tall printed banner on a white wall'),
    featured: false,
  },
];
